---
name: Pre-release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  pre-release:
    name: Create Pre-release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Pre-release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: latest
          name: Development Build
          prerelease: true
          generate_release_notes: true
          files: audio-share.sh
